name: Publish All Debian Packages

on:
  release:
    types: [prereleased, released]

  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (E.G. v0.10.0-rc.1, v0.10.0). Corresponding git tag must already exist."
        required: true
        type: string

env:
  version: ${{ inputs.version || github.ref_name }}

permissions:
  id-token: write
  contents: write

jobs:
  publish-mybinary: # TODO(template) update for the project
    name: Publish Mybinary ${{ matrix.arch }} Debian # TODO(template) update for the project
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on:
      labels: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Build and Publish Mybinary # TODO(template) update for the project
        uses: ./.github/actions/debian
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gitref: ${{ env.version }}
          crate_dir: mybinary # TODO(template) update for the project
          service: miden-mybinary # TODO(template) update for the project
          package: mybinary # TODO(template) update for the project
          crate: miden-mybinary # TODO(template) update for the project
          arch: ${{ matrix.arch }}

  